#!/usr/bin/env python3
"""Loom: compile the knowledge layer into the files an SDD engine reads.

Engines read their own files, not docs/. This assembles them from the authored
documents and writes them to the paths declared in docs/loom.yaml `engine:`.
Every output opens with a GENERATED marker and must never be hand-edited.

Outputs:
  constitution  conventions + accepted-ADR digest + rules + invariants +
                anti-goals + rejected-ADR digest + glossary
  spec          per-epic seed spec: each task's ## Spec + contracts + packages

Usage:
  compile.py                          write every configured output
  compile.py --epic epic-<slug>       also write that epic's seed spec
  compile.py --print                  print to stdout, write nothing
  compile.py --check                  exit 1 if any output is missing or stale
Naive line parsing of loom.yaml (stdlib only, no deps) — same as the other
scripts in this directory.
"""
import re
import sys
from pathlib import Path

DOCS = Path("docs")
MARK = "<!-- GENERATED by scripts/loom/compile.py — do not edit; "
CFG = DOCS / "loom.yaml"


def config():
    """Parse the `engine:` block: one level of indentation, `key: value`."""
    cfg, in_engine = {}, False
    if not CFG.exists():
        return cfg
    for line in CFG.read_text(encoding="utf-8").splitlines():
        if re.match(r"^engine:\s*$", line):
            in_engine = True
            continue
        if in_engine:
            if line[:1] not in (" ", "\t"):
                break
            m = re.match(r"^\s+([a-z_]+):\s*(.*)$", line)
            if m:
                cfg[m.group(1)] = m.group(2).strip().strip("\"'")
    return cfg


def frontmatter(lines):
    if not lines or lines[0].strip() != "---":
        return {}
    fm, key = {}, None
    for line in lines[1:]:
        if line.strip() == "---":
            return fm
        if re.match(r"^\S[^:]*:", line):
            key, _, v = line.partition(":")
            key, v = key.strip(), v.strip().strip("\"'")
            fm[key] = [] if v in ("", "[]") else v
            if v.startswith("[") and v.endswith("]") and v != "[]":
                fm[key] = [x.strip().strip("'\"") for x in v[1:-1].split(",")]
        elif key and line.strip().startswith("- "):
            if not isinstance(fm[key], list):
                fm[key] = []
            fm[key].append(line.strip()[2:].strip().strip("'\""))
    return fm


def docs_with_id(prefix, root=DOCS):
    """[(id, frontmatter, text, path)] for docs whose frontmatter id starts with prefix."""
    out = []
    for f in sorted(root.rglob("*.md")):
        try:
            text = f.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if text.lstrip().startswith("<!-- GENERATED"):
            continue
        fm = frontmatter(text.splitlines())
        fid = fm.get("id")
        if isinstance(fid, str) and fid.startswith(prefix):
            out.append((fid, fm, text, f))
    return out


def section(text, heading):
    """Body of the first `## <heading>` section (case-insensitive), or ''."""
    want = heading.lower()
    keep, out = False, []
    for line in text.splitlines():
        if line.startswith("## "):
            if keep:
                break
            keep = line[3:].strip().lower().startswith(want)
            continue
        if keep:
            out.append(line)
    return "\n".join(out).strip()


def embed(path):
    """A document's body, ready to nest under a compiled heading: frontmatter and
    its own H1 removed so the output keeps one heading hierarchy."""
    text = path.read_text(encoding="utf-8")
    if text.lstrip().startswith("---"):
        text = text.split("---", 2)[-1]
    out = [ln for ln in text.strip().splitlines()]
    while out and (not out[0].strip() or out[0].startswith("# ")):
        out.pop(0)
    return "\n".join(out).strip()


def first_sentence(text, limit=240):
    t = " ".join(text.split())
    if not t:
        return ""
    m = re.search(r"^(.{1,%d}?[.!])\s" % limit, t + " ")
    return (m.group(1) if m else t[:limit]).strip()


def adr_digest(adrs, status):
    """Decision + reason + consequence. Never the options, never the debate:
    an engine needs the constraint, not the history that produced it."""
    rows = []
    for aid, fm, text, _ in adrs:
        if fm.get("status") != status:
            continue
        decision = first_sentence(section(text, "Decision")) or aid
        reason = first_sentence(section(text, "Context") or section(text, "Rationale"))
        conseq = first_sentence(section(text, "Consequences"))
        rows.append((aid, fm, decision, reason, conseq))
    return rows


def compile_constitution():
    lines = [
        MARK + "source: docs/ -->",
        "# Project constitution", "",
        "Assembled by Loom from the project's knowledge layer. Every statement",
        "here is binding on generated code. To change one, change its source",
        "document under `docs/` and re-run `/loom:compile` — edits to this file",
        "are lost on the next compile.", "",
    ]

    glossary = DOCS / "product" / "GLOSSARY.md"
    if glossary.exists():
        lines += ["## Vocabulary", "",
                  "Use these terms verbatim in identifiers, messages and docs.", "",
                  embed(glossary), ""]

    vision = DOCS / "product" / "VISION.md"
    if vision.exists():
        anti = section(vision.read_text(encoding="utf-8"), "Anti-goals")
        if anti:
            lines += ["## Out of bounds (anti-goals)", "",
                      "Do not build these, and do not build toward them.", "",
                      anti, ""]

    rules = DOCS / "product" / "RULES.md"
    if rules.exists():
        lines += ["## Domain rules (binding)", "",
                  "Reproduce these exactly — formulas, thresholds, rounding and",
                  "boundaries are given, not chosen. Never infer a missing one.", "",
                  embed(rules), ""]

    adrs = docs_with_id("ADR-")
    accepted = adr_digest(adrs, "accepted")
    if accepted:
        lines += ["## Decisions in force", "",
                  "| Decision | Because | Consequence | ADR |", "|---|---|---|---|"]
        for aid, fm, dec, why, con in accepted:
            lines.append(f"| {dec} | {why or '—'} | {con or '—'} | `{aid}` |")
        lines.append("")
        enforced = [(a, f.get("enforced")) for a, f, _, _, _ in accepted
                    if f.get("enforced") not in (None, "", [], "none")]
        if enforced:
            lines += ["Enforced mechanically (do not weaken): " +
                      ", ".join(f"`{a}` ({e})" for a, e in enforced), ""]

    rejected = adr_digest(adrs, "rejected")
    if rejected:
        lines += ["## Ruled out (do not propose these again)", "",
                  "| Not this | Because | ADR |", "|---|---|---|"]
        for aid, _, dec, why, _ in rejected:
            lines.append(f"| {dec} | {why or '—'} | `{aid}` |")
        lines.append("")

    conv = sorted((DOCS / "conventions").glob("*.md")) if (DOCS / "conventions").is_dir() else []
    if conv:
        lines += ["## Conventions", ""]
        for c in conv:
            lines += [f"### {c.stem}", "", embed(c), ""]

    bb = DOCS / "architecture" / "building-blocks.md"
    if bb.exists():
        text = bb.read_text(encoding="utf-8")
        forb = section(text, "Forbidden dependencies") or section(text, "Boundaries")
        if forb:
            lines += ["## Structural boundaries", "",
                      "A forbidden dependency is a blocker to report, not an",
                      "obstacle to work around.", "", forb, ""]

    return "\n".join(lines).rstrip() + "\n"


def compile_spec(epic_id):
    epics = [(i, fm, t, p) for i, fm, t, p in docs_with_id("epic-") if i == epic_id]
    if not epics:
        return None
    _, efm, etext, epath = epics[0]
    root = epath.parent
    lines = [
        MARK + f"source: {root} -->",
        f"# {epic_id} — seed spec", "",
        f"Epic status: {efm.get('status', '?')}. "
        f"Appetite: {efm.get('appetite', '—')}. "
        f"Criticality: {efm.get('criticality', '—')}.", "",
        "This is a seed for the engine's own spec/plan step, compiled from the",
        "epic's approved task specs. The plan, the tests and the code are yours;",
        "behavior and acceptance below are not negotiable — a spec that cannot be",
        "satisfied honestly is a defect to report back, not to route around.", "",
    ]
    scope = section(etext, "Scope") or section(etext, "Goal")
    if scope:
        lines += ["## Epic scope", "", scope, ""]

    contracts = sorted((root / "contracts").rglob("*")) if (root / "contracts").is_dir() else []
    contracts = [c for c in contracts if c.is_file()]
    if contracts:
        lines += ["## Contracts (source of truth — do not redefine)", ""]
        lines += [f"- `{c}`" for c in contracts]
        lines.append("")

    tasks = sorted((root / "tasks").glob("*.md")) if (root / "tasks").is_dir() else []
    lines += ["## Tasks", ""]
    count = 0
    for t in tasks:
        text = t.read_text(encoding="utf-8")
        fm = frontmatter(text.splitlines())
        if fm.get("status") != "approved":
            continue
        spec = section(text, "Spec")
        if not spec:
            continue
        count += 1
        pkgs = fm.get("packages") or []
        pkgs = pkgs if isinstance(pkgs, list) else [pkgs]
        dep = fm.get("depends_on") or []
        dep = dep if isinstance(dep, list) else [dep]
        lines += [f"### {fm.get('id', t.stem)}", "",
                  f"- rigor (cost of being wrong): **{fm.get('rigor', '?')}**",
                  f"- packages: {', '.join(f'`{p}`' for p in pkgs) or '—'}",
                  f"- depends on: {', '.join(f'`{d}`' for d in dep) or '—'}", ""]
        for p in pkgs:
            skill = Path(p) / "SKILL.md"
            if skill.exists():
                lines.append(f"- package contract: `{skill}` (read it; keep its "
                             f"Boundaries section sacred)")
        lines += ["", spec, ""]
    if not count:
        lines += ["_No approved task specs in this epic yet._", ""]
    return "\n".join(lines).rstrip() + "\n"


def targets(cfg, epic):
    """[(label, path, content)] for everything configured."""
    out = []
    if cfg.get("constitution"):
        out.append(("constitution", Path(cfg["constitution"]), compile_constitution()))
    if epic:
        content = compile_spec(epic)
        if content is None:
            print(f"ERROR: no epic '{epic}' found under docs/", file=sys.stderr)
            sys.exit(1)
        spec_dir = cfg.get("spec_dir")
        if spec_dir:
            out.append(("spec", Path(spec_dir) / f"{epic}.md", content))
        else:
            out.append(("spec", None, content))
    return out


def main(argv):
    epic = None
    if "--epic" in argv:
        epic = argv[argv.index("--epic") + 1]
    cfg = config()
    if not cfg.get("name"):
        print("ERROR: no engine configured — set engine.name and its paths in "
              "docs/loom.yaml before compiling", file=sys.stderr)
        return 1

    items = targets(cfg, epic)
    if not items:
        print("ERROR: engine is named but no output paths are configured "
              "(engine.constitution / engine.spec_dir)", file=sys.stderr)
        return 1

    if "--print" in argv:
        for label, path, content in items:
            print(f"===== {label} → {path or '(no path configured)'}")
            print(content)
        return 0

    if "--check" in argv:
        stale = []
        for label, path, content in items:
            if path is None:
                stale.append(f"{label}: no output path configured")
            elif not path.exists():
                stale.append(f"{label}: {path} missing")
            elif path.read_text(encoding="utf-8") != content:
                stale.append(f"{label}: {path} is stale")
        for s in stale:
            print(f"ERROR: {s}", file=sys.stderr)
        print(f"-- outputs: {len(items)}, stale: {len(stale)}")
        if stale:
            print("GATE FAILED — run /loom:compile", file=sys.stderr)
            return 1
        print("GATE PASSED")
        return 0

    for label, path, content in items:
        if path is None:
            print(f"WARN: {label} has no configured path — skipped", file=sys.stderr)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path} ({label}, {len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
