#!/usr/bin/env python3
"""Loom: generate docs/INDEX.md from document frontmatter.

Usage:
  index_gen.py            write docs/INDEX.md
  index_gen.py --print    print the table to stdout only
Naive frontmatter parser (top-level `key: value` between --- fences) — no deps.
"""
import sys
from datetime import date
from pathlib import Path
from config import ConfigError, project_config, target, require_targets, usage

DOCS = Path("docs")


def frontmatter(path: Path):
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (UnicodeDecodeError, OSError):
        return None
    if not lines or lines[0].lstrip().startswith("<!-- GENERATED"):
        return None
    if lines[0].strip() != "---":
        return None
    fm = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return fm
        if ":" in line and not line.startswith((" ", "\t", "-")):
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip()
    return None


def main(argv):
    if "--help" in argv:
        print(usage("index_gen.py", "[--print] [--help]", "Generate or print the configured document index."))
        return 0
    try:
        config, base = project_config()
        docs = base / target(config, "docs", "docs")
    except ConfigError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    for error in require_targets([docs]):
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    rows = []
    for f in sorted(docs.rglob("*.md")):
        if f.name == "INDEX.md":
            continue
        fm = frontmatter(f)
        if fm and "status" in fm:
            rows.append((fm.get("id", "?"), fm["status"],
                         fm.get("updated", "?"), str(f)))

    lines = [
        "<!-- GENERATED by scripts/loom/index_gen.py — do not edit -->",
        f"# Loom document index ({date.today().isoformat()})", "",
        "| ID | Status | Updated | Path |", "|---|---|---|---|",
    ]
    lines += [f"| {i} | {s} | {u} | {p} |" for i, s, u, p in rows]
    out = "\n".join(lines) + "\n"

    if "--print" in argv or "--gate" in argv:
        print(out)
    else:
        (docs / "INDEX.md").write_text(out, encoding="utf-8")
        print(f"wrote {docs / 'INDEX.md'} ({len(rows)} documents)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
