#!/usr/bin/env python3
"""Loom: generate docs/roadmap/ROADMAP.md from epic frontmatter.

Reads docs/roadmap/epics/*/epic.md. Validates:
  - epic id equals its bundle directory name
  - depends_on references resolve to existing epics
  - the dependency graph is acyclic
Generates a status table + mermaid dependency DAG. Never edit ROADMAP.md by hand.

Usage:
  roadmap_gen.py            write docs/roadmap/ROADMAP.md
  roadmap_gen.py --print    print to stdout only
  roadmap_gen.py --gate     exit 1 on validation errors (also implied on write)
"""
import re
import sys
from datetime import date
from pathlib import Path
from config import ConfigError, project_config, target, require_targets, usage

EPICS = Path("docs/roadmap/epics")
OUT = Path("docs/roadmap/ROADMAP.md")


def frontmatter(lines):
    if not lines or lines[0].strip() != "---":
        return {}
    fm, key = {}, None
    for line in lines[1:]:
        if line.strip() == "---":
            return fm
        if re.match(r"^\S[^:]*:", line):
            key, _, v = line.partition(":")
            key, v = key.strip(), v.split("#")[0].strip()
            fm[key] = [] if v in ("", "[]") else v
            if v.startswith("[") and v.endswith("]") and v != "[]":
                fm[key] = [x.strip().strip("'\"") for x in v[1:-1].split(",")]
        elif key and line.strip().startswith("- "):
            if not isinstance(fm[key], list):
                fm[key] = []
            fm[key].append(line.strip()[2:].split("#")[0].strip().strip("'\""))
    return fm


def find_cycle(graph):
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {n: WHITE for n in graph}
    def dfs(n, path):
        color[n] = GRAY
        for m in graph.get(n, []):
            if m not in color:
                continue
            if color[m] == GRAY:
                return path + [n, m]
            if color[m] == WHITE:
                r = dfs(m, path + [n])
                if r:
                    return r
        color[n] = BLACK
        return None
    for n in graph:
        if color[n] == WHITE:
            r = dfs(n, [])
            if r:
                return r
    return None


def main(argv):
    if "--help" in argv:
        print(usage("roadmap_gen.py", "[--print|--gate]", "Validate and generate the configured roadmap."))
        return 0
    try:
        config, base = project_config()
        epics_dir = base / target(config, "epics", "docs/roadmap/epics")
        out_path = base / target(config, "roadmap", "docs/roadmap") / "ROADMAP.md"
    except ConfigError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    for error in require_targets([epics_dir]):
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    epics, errors = {}, []
    for f in sorted(epics_dir.glob("*/epic.md")):
        fm = frontmatter(f.read_text(encoding="utf-8").splitlines())
        eid = fm.get("id", "?")
        if eid != f.parent.name:
            errors.append(f"id '{eid}' != directory name '{f.parent.name}' ({f})")
        deps = fm.get("depends_on", [])
        epics[eid] = {
            "status": fm.get("status", "?"),
            "goal": fm.get("goal", ""),
            "criticality": fm.get("criticality", "?"),
            "appetite": fm.get("appetite", "?"),
            "deps": deps if isinstance(deps, list) else [deps],
        }

    graph = {}
    for eid, e in epics.items():
        for d in e["deps"]:
            if d not in epics:
                errors.append(f"{eid}: depends_on '{d}' does not resolve")
        graph[eid] = [d for d in e["deps"] if d in epics]
    cyc = find_cycle(graph)
    if cyc:
        errors.append("dependency cycle: " + " -> ".join(cyc))

    order = {"must": 0, "should": 1, "could": 2, "wont": 3}
    rows = sorted(epics.items(), key=lambda kv: (order.get(kv[1]["criticality"], 9), kv[0]))
    lines = [
        "<!-- GENERATED by scripts/loom/roadmap_gen.py — do not edit -->",
        f"# Roadmap ({date.today().isoformat()})", "",
        "| Epic | Status | Criticality | Appetite | Depends on | Goal |",
        "|---|---|---|---|---|---|",
    ]
    for eid, e in rows:
        lines.append(f"| {eid} | {e['status']} | {e['criticality']} | "
                     f"{e['appetite']} | {', '.join(e['deps']) or '—'} | {e['goal']} |")
    lines += ["", "```mermaid", "graph LR"]
    for eid, e in rows:
        lines.append(f"  {eid}")
        for d in e["deps"]:
            lines.append(f"  {d} --> {eid}")
    lines += ["```", ""]
    out = "\n".join(lines)

    approved = [eid for eid, e in epics.items() if e["status"] == "approved"]
    if len(approved) > 1:
        errors.append("more than one approved epic: " + ", ".join(sorted(approved)))
    for err in errors:
        print(f"ERROR: {err}", file=sys.stderr)
    if "--print" in argv:
        print(out)
    elif not errors and "--gate" not in argv:
        out_path.write_text(out, encoding="utf-8")
        print(f"wrote {out_path} ({len(epics)} epics)")
    print(f"-- epics: {len(epics)}, errors: {len(errors)}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
