#!/usr/bin/env python3
"""Loom: generate docs/product/UC-DIAGRAM.md — an actor<->use case UML diagram.

Reads docs/product/ACTORS.md (ACTOR-* table rows) and
docs/product/use-cases/UC-*.md (frontmatter: primary_actor, secondary_actors,
includes, extends). Renders a Mermaid flowchart: actors as plain nodes, use
cases as stadium nodes, associations as solid edges, <<include>>/<<extend>>
as labeled dashed edges. Mermaid has no native UML use-case diagram type —
this is the flowchart-based convention this repo uses (see roadmap_gen.py).

Validates that every primary_actor/secondary_actors/includes/extends
reference resolves to a real ACTOR-*/UC-* id.

Usage:
  uc_diagram_gen.py            write docs/product/UC-DIAGRAM.md
  uc_diagram_gen.py --print    print to stdout only
  uc_diagram_gen.py --gate     exit 1 on validation errors (also implied on write)
"""
import re
import sys
from datetime import date
from pathlib import Path
from config import ConfigError, project_config, target, require_targets, usage

ACTORS = Path("docs/product/ACTORS.md")
USE_CASES = Path("docs/product/use-cases")
OUT = Path("docs/product/UC-DIAGRAM.md")

ACTOR_ROW_RE = re.compile(r"^\|\s*(ACTOR-[a-z0-9][a-z0-9-]*[a-z0-9])\s*\|\s*([^|]*)\|")


def frontmatter(lines):
    if not lines or lines[0].strip() != "---":
        return {}
    fm, key = {}, None
    for line in lines[1:]:
        if line.strip() == "---":
            return fm
        if re.match(r"^\S[^:]*:", line):
            key, _, v = line.partition(":")
            key, v = key.strip(), v.split("#")[0].strip()
            fm[key] = [] if v in ("", "[]") else v
            if v.startswith("[") and v.endswith("]") and v != "[]":
                fm[key] = [x.strip().strip("'\"") for x in v[1:-1].split(",") if x.strip()]
        elif key and line.strip().startswith("- "):
            if not isinstance(fm[key], list):
                fm[key] = []
            fm[key].append(line.strip()[2:].split("#")[0].strip().strip("'\""))
    return fm


def as_list(v):
    if not v:
        return []
    return v if isinstance(v, list) else [v]


def main(argv):
    if "--help" in argv:
        print(usage("uc_diagram_gen.py", "[--print|--gate]", "Validate and generate the configured use-case diagram."))
        return 0
    try:
        config, base = project_config()
        product = base / target(config, "product", "docs/product")
        actors_path = product / "ACTORS.md"
        use_cases = product / "use-cases"
        out_path = product / "UC-DIAGRAM.md"
    except ConfigError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    for error in require_targets([product, use_cases]):
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    errors = []

    actors = {}
    if actors_path.exists():
        for line in actors_path.read_text(encoding="utf-8").splitlines():
            m = ACTOR_ROW_RE.match(line.strip())
            if m:
                actors[m.group(1)] = m.group(2).strip()

    ucs = {}
    for f in sorted(use_cases.glob("UC-*.md")):
        fm = frontmatter(f.read_text(encoding="utf-8").splitlines())
        uid = fm.get("id", "?")
        if uid != f.stem:
            errors.append(f"id '{uid}' != filename '{f.stem}' ({f})")
        ucs[uid] = {
            "primary": fm.get("primary_actor", ""),
            "secondary": as_list(fm.get("secondary_actors", [])),
            "includes": as_list(fm.get("includes", [])),
            "extends": as_list(fm.get("extends", [])),
        }

    for uid, e in ucs.items():
        for a in ([e["primary"]] if e["primary"] else []) + e["secondary"]:
            if a not in actors:
                errors.append(f"{uid}: actor '{a}' does not resolve in ACTORS.md")
        for rel, targets in (("includes", e["includes"]), ("extends", e["extends"])):
            for t in targets:
                if t not in ucs:
                    errors.append(f"{uid}: {rel} '{t}' does not resolve to a UC-*.md")

    lines = [
        "<!-- GENERATED by scripts/loom/uc_diagram_gen.py — do not edit -->",
        f"# Use case diagram ({date.today().isoformat()})", "",
        "```mermaid", "flowchart LR",
    ]
    for aid in sorted(actors):
        lines.append(f"  {aid}[{aid}]")
    for uid in sorted(ucs):
        lines.append(f"  {uid}([{uid}])")
    for uid, e in sorted(ucs.items()):
        if e["primary"]:
            lines.append(f"  {e['primary']} --- {uid}")
        for a in e["secondary"]:
            lines.append(f"  {a} -.-> {uid}")
        for t in e["includes"]:
            lines.append(f"  {uid} -.->|<<include>>| {t}")
        for t in e["extends"]:
            lines.append(f"  {uid} -.->|<<extend>>| {t}")
    lines += ["```", ""]
    out = "\n".join(lines)

    for err in errors:
        print(f"ERROR: {err}", file=sys.stderr)
    if "--print" in argv:
        print(out)
    elif not errors and "--gate" not in argv:
        out_path.write_text(out, encoding="utf-8")
        print(f"wrote {out_path} ({len(actors)} actors, {len(ucs)} use cases)")
    print(f"-- actors: {len(actors)}, use cases: {len(ucs)}, errors: {len(errors)}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
